mr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  swerve_front_right_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: swerve_front_right_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  wheel_front_right_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_right_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  swerve_back_right_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: swerve_back_right_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  wheel_back_right_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_right_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  swerve_back_left_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: swerve_back_left_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  wheel_back_left_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_left_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  swerve_front_left_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: swerve_front_left_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
  wheel_front_left_link_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_left_link
    pid: {p: 10.0, i: 0.01, d: 0.0}
